"""empty message

Revision ID: 2660c903aaf1
Revises: 6f23f1e08464
Create Date: 2023-11-10 12:41:01.845036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2660c903aaf1'
down_revision = '6f23f1e08464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_damage_dealt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_damage_taken', sa.Integer(), nullable=True))
        batch_op.drop_column('totalDamageTaken')
        batch_op.drop_column('totalDamageDealt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalDamageDealt', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalDamageTaken', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_damage_taken')
        batch_op.drop_column('total_damage_dealt')

    # ### end Alembic commands ###
