"""empty message

Revision ID: 2dcb4bf857d8
Revises: be05c5f674d1
Create Date: 2023-11-10 12:57:07.635872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcb4bf857d8'
down_revision = 'be05c5f674d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.alter_column('kda',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.alter_column('kda',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
