"""empty message

Revision ID: 48205d3d8871
Revises: d95461e0acfa
Create Date: 2023-11-10 12:11:32.042942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48205d3d8871'
down_revision = 'd95461e0acfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kda', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.drop_column('kda')

    # ### end Alembic commands ###
