"""empty message

Revision ID: 6f23f1e08464
Revises: 48205d3d8871
Create Date: 2023-11-10 12:33:07.516903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f23f1e08464'
down_revision = '48205d3d8871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.drop_column('ranked_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranked_by', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
