"""empty message

Revision ID: 7e014a96c8ef
Revises: 04dac04cfc1e
Create Date: 2023-11-05 17:36:17.637702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e014a96c8ef'
down_revision = '04dac04cfc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=False),
    sa.Column('perf_metric', sa.String(), nullable=False),
    sa.Column('leaderboard_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboards.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('performance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('perf_metric', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('leaderboard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboards.id'], name='performance_leaderboard_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='performance_pkey')
    )
    op.drop_table('performances')
    # ### end Alembic commands ###
