"""initial setup

Revision ID: a13de8991bb3
Revises: 
Create Date: 2023-10-25 23:32:10.988281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13de8991bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('puuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('puuid')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_puuid', sa.String(), nullable=False),
    sa.Column('friended_by_puuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['friended_by_puuid'], ['users.puuid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ranked_by', sa.String(), nullable=False),
    sa.Column('number_of_games', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.puuid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('perf_metric', sa.String(), nullable=False),
    sa.Column('leaderboard_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboards.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance')
    op.drop_table('leaderboards')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
