"""empty message

Revision ID: b9cb91fdf6f3
Revises: ebd5d2847c1c
Create Date: 2023-11-12 15:13:39.475860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cb91fdf6f3'
down_revision = 'ebd5d2847c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_friendship', ['friend_puuid', 'friended_by_puuid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['puuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint('uq_friendship', type_='unique')

    # ### end Alembic commands ###
