"""empty message

Revision ID: be05c5f674d1
Revises: 2660c903aaf1
Create Date: 2023-11-10 12:41:48.019205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be05c5f674d1'
down_revision = '2660c903aaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.drop_column('perf_metric')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perf_metric', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
