"""empty message

Revision ID: d95461e0acfa
Revises: 7e014a96c8ef
Create Date: 2023-11-10 10:59:29.502852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95461e0acfa'
down_revision = '7e014a96c8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deaths', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalDamageDealt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalDamageTaken', sa.Integer(), nullable=True))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('totalDamageTaken')
        batch_op.drop_column('totalDamageDealt')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')
        batch_op.drop_column('deaths')
        batch_op.drop_column('kills')

    # ### end Alembic commands ###
