"""empty message

Revision ID: df506ffd7590
Revises: 4ea89f233743
Create Date: 2023-11-03 23:43:05.695653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df506ffd7590'
down_revision = '4ea89f233743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###
