"""empty message

Revision ID: ebd5d2847c1c
Revises: 
Create Date: 2023-11-12 14:38:36.984133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd5d2847c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=False),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('puuid'),
    sa.UniqueConstraint('puuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_puuid', sa.String(), nullable=False),
    sa.Column('friended_by_puuid', sa.String(), nullable=False),
    sa.Column('friend_profile_icon', sa.String(), nullable=True),
    sa.Column('friend_summoner_name', sa.String(), nullable=False),
    sa.Column('friend_region', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['friended_by_puuid'], ['users.puuid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=True),
    sa.Column('number_of_games', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.puuid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=False),
    sa.Column('leaderboard_id', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=True),
    sa.Column('total_damage_taken', sa.Integer(), nullable=True),
    sa.Column('kda', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboards.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performances')
    op.drop_table('leaderboards')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
